# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entry',
            field=models.TextField(blank=True, help_text='Enter your entry'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.TextField(blank=True, help_text='Enter a title'),
        ),
    ]
