# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170415_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x103d69b70>', on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
    ]
